name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install cloudflared
      run: |
        curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
        chmod +x cloudflared
        sudo mv cloudflared /usr/local/bin/

    - name: Install dependencies
      run: |
        npm install

    - name: Build Next.js app
      run: |
        npm run build

    - name: Create .ssh directory
      run: |
        mkdir -p ~/.ssh

    - name: Install sshpass
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass

    - name: Configure SSH
      run: |
        echo "Host mertalukas
          HostName ssh.mertalukas.cz
          User root
          ProxyCommand cloudflared access ssh --hostname %h --service-token-id ${{ secrets.CLOUDFLARE_SERVICE_TOKEN_ID }} --service-token-secret ${{ secrets.CLOUDFLARE_SERVICE_TOKEN_SECRET }}
        " >> ~/.ssh/config

    - name: Deploy Next.js app files
      env:
        SSHPASS: ${{ secrets.SSH_PASSWORD }}
      run: |
        sshpass -e scp -o StrictHostKeyChecking=no -r .next public package.json next.config.js root@mertalukas:/var/www/html/public/museum/

    - name: Start/Restart Next.js app on server
      env:
        SSHPASS: ${{ secrets.SSH_PASSWORD }}
      run: |
        sshpass -e ssh -o StrictHostKeyChecking=no root@mertalukas << 'EOF'
          cd /var/www/html/public/museum
          npm install --omit=dev
          pm2 start "npm run start" --name museum --watch -- --port 6040 || pm2 restart museum
        EOF
